esphome:
  name: fancontrol
  platform: ESP8266
  board: d1_mini_pro
  includes: 
    - ITHO/c1101.h
  libraries: 
    - https://github.com/CoMPaTech/esphome_itho.git

wifi:
  ssid: "secret"
  password: "evenmoresecret"

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: 'fan'

ota:
  password: 'fan'

switch:
- platform: custom
  lambda: |-
    auto fansendjoin = new FanSendIthoJoin();
    App.register_component(fansendjoin);
    return {fansendjoin};
  switches:
    name: "FanSendJoin"

output:
  - platform: custom
    type: float
    outputs:
      id: fanoutput
    lambda: |-
      auto fanoutput = new FanOutput();
      App.register_component(fanoutput);
      return {fanoutput};

text_sensor:
- platform: custom
  lambda: |-
    auto fanrecv = new FanRecv();
    App.register_component(fanrecv);
    return {fanrecv->fanspeed};

  text_sensors:
    - name: "FanSpeed"

fan:
  - platform: speed
    output: fanoutput
    id: fanoutput
    name: "Fan"
